### ISSUE TITLE
Gelbes Geländer [FEATURE]

### ISSUE THREAD

**Issue by Acyclovic** [SimBuildings/IuvatResources#1]
**Welches Feature möchtest du vorschlagen?**
Beschreibe ausführlich welchen Block du vorschlägst. Mit welchen anderen Blöcken sollte die Textur zusammen verwendet werden? Wieso hältst du den Block für wichtig und relevant?

⸻⸻ Ich schlage ein gelbes Geländer als Block für das Iuvat Pack vor. Dieses Geländer soll zusammen mit der Eisenfalltüre in den Tunneln der Metro verwendet werden (hauptsächlich in Kehranlagen). Ich halte dieses Geländer für wichtig, da es viel mehr Detail in diese Anlagen bringen und die Metro noch realistischer machen würde.

**Wie soll das Feature umgesetzt werden?**
Welcher Block soll ersetzt werden? Handelt es sich um einen Block, eine 3D Textur oder sonstiges? Welche Funktionen sollte der Block erfüllen?
Beschreibe ausführlich und deutlich, wie das Feature umgesetzt werden soll.
_Bitte verlinke mehrere Referenzbilder_

⸻⸻ Ersezt werden soll die Wirr-Falltüre, da es sich um einen Block handelt. Die Falltüre scheint mir optimal, da sie "fest ist" und damit den Zweck eines Geländers erfüllt und sich ausrichten lässt, damit man das Geländer und alle Richtungen  drehen kann.

⸻⸻ Umgesetzt werden soll das Feature wie folgend aufgezeigt: Es handelt sich bei einer 64x64 Textur lediglich um ein umgedrehtes gelbes U mit eckigen Ecken, welches 8x8 Pixel dick sein soll. Dadurch entsteht quasi ein Rahmen (siehe Referenzen). In der Mitte des Rahmens befindet sich eine dünnere Querstange als Stabilisator.

⸻⸻ Referenzbilder: https://media.discordapp.net/attachments/294120012791283712/861274257169711124/unknown.png

**Zusätzlicher Kontext**
Füge hier weiteren Kontext oder Screenshots zu der Funktionsanforderung hinzu.

⸻⸻ Funktionsanforderung: Drehbar.

Gez. Consi

**Comment by sotterbeck** [comment]
https://github.com/SimBuildings/IuvatResources/commit/6248aeabd7a48044883d6d9aeab76164a0770f45
https://github.com/SimBuildings/IuvatResources/commit/557cff15e258db41622424dd187d6b450c197654
https://github.com/SimBuildings/IuvatResources/commit/99ee91204c98e2fd72254870e16589e28cbba753
