### ISSUE TITLE
FACKELN unsichtbar machen [FEATURE]

### ISSUE THREAD

**Issue by Acyclovic** [SimBuildings/IuvatResources#5]
**Welches Feature möchtest du vorschlagen?**

Es wäre cool wenn Fackeln unsichtbar wären, damit die Gebäude wieder mal bessere aussehen.

danke

Beschreibe ausführlich welchen Block du vorschlägst. Mit welchen anderen Blöcken sollte die Textur zusammen verwendet werden? Wieso hältst du den Block für wichtig und relevant?

**Wie soll das Feature umgesetzt werden?**
Welcher Block soll ersetzt werden? Handelt es sich um einen Block, eine 3D Textur oder sonstiges? Welche Funktionen sollte der Block erfüllen?
Beschreibe ausführlich und deutlich, wie das Feature umgesetzt werden soll.
_Bitte verlinke mehrere Referenzbilder_

**Zusätzlicher Kontext**
Füge hier weiteren Kontext oder Screenshots zu der Funktionsanforderung hinzu.

**Comment by Acyclovic** [comment]
Hello, I would like to know how long it will approximately take to include the textures into the pack.

regards
consi PM

Office of the Prime Minister of Iuvat
Directorate II, PM assistance
Villa Iuvatia
Harhusenstraße 1
IU 11011 Bizern

**Comment by sotterbeck** [comment]
https://github.com/SimBuildings/IuvatResources/commit/f35ef8d47af1271e790b94ffd726ff58ea486a20
